import json

from reviewer.simulated_doctor import SimulatedDoctor

from metrics.reward_tracker import calculate_reward

from learning.correction_memory import save_memory


# Read draft generated by Part 1

with open(
    "outputs/summary.json",
    "r"
) as f:

    draft = json.load(f)


# Simulated Doctor Review

doctor = SimulatedDoctor()

edited = doctor.review(draft)


# Calculate Reward

reward = calculate_reward(
    draft,
    edited
)

print(
    f"Reward Score: {reward}"
)


# Save Learning Memory

save_memory(
    {
        "reward": reward
    }
)


# Save Doctor Edited Version

with open(
    "outputs/doctor_edited.json",
    "w"
) as f:

    json.dump(
        edited,
        f,
        indent=4
    )